### ISSUE TITLE
Card-Support

### ISSUE THREAD

**Issue by Muwak77** [Daimakaicho/better-entity-link#2]
Could we get an update that supports cards? 

Pushing the module to foundry V9 would be great too.

**Comment by Daimakaicho** [comment]
Hello @Muwak77 ! I don't have a lot of time to develop Foundry's module anymore, but I did a update today (v1.1). Module is now updated to V9 and I added a basic card support ("shuffle", "draw", "pass", "deal" and "reset" actions). Everything looks fine, but as I didn't look at cards yet, I can't promise there is absolutly no bugs. Feedbacks are welcome :)

**Comment by Muwak77** [comment]
Thank you so much. Ich absolutely understand the time-issue. It's quiet the same for me and i am more than happy with the additions.
