### ISSUE TITLE
Feature Request: Pop-up instead of pop-down on entities in chat

### ISSUE THREAD

**Issue by esheyw** [Daimakaicho/better-entity-link#3]
Not sure if bug report or feature request. The title would solve this, but on further experimenting it may be a simpler fix. 

Currently if you, for example, right click on a table that is the only text in its message, and its the bottom message in chat, the roll button gets cut off until you scroll down: https://gfycat.com/velvetyspecificacouchi

As you can see, once you've scrolled down once, it fixes itself for a while, but switching tabs away from/back to chat resets it to non-working. BEL is the only active module in that world.

**Comment by Daimakaicho** [comment]
Thanks for your feedback! I'll take a look if and how I can add this.

**Comment by Daimakaicho** [comment]
This behavior is deeply tied to Foundry. It may be possible to change it but a change would imply modification on all context menus in Foundry. I  planned this module to provide a way to easy add more useful context menu on existing entity link, not to change context menu behavior. I prefer not to trick with native Foundry, at least not in this module.

**Comment by esheyw** [comment]
Fair enough, its not hard to work around once you figure it out.
