### ISSUE TITLE
Bug? Feature Request? Doesn't work with PF2e Journal Styling.

### ISSUE THREAD

**Issue by esheyw** [Daimakaicho/better-entity-link#4]
Not sure if this is fixable on your end or has to be on theirs, but the (by default on) custom journal sheet entry PF2e uses breaks this mod's functionality. It's not a dealbreaker, but compatibility would be nice, if its easy to do? 

https://gfycat.com/RedFatalJuliabutterfly

**Comment by Daimakaicho** [comment]
Thanks for your feedaback! I do not use PF2e, but I noticed same issues on custom journal on dnd5e too. I guess it's a more global issue. I'll look to fix this.

**Comment by Daimakaicho** [comment]
Ok this is a more complex bug than I thought. In particular it probably breaks in many situations since v9. I think I have a fix, I just need some time to test. A new version may get out by the end of the week.

**Comment by Daimakaicho** [comment]
A new released version (v1.1.1) should fix this issue.
